### ISSUE TITLE
How do you validate the token?

### ISSUE THREAD

**Issue by dbvcode** [MohammedFaragallah/feathers-authentication-management-ts#13]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
First of all, thanks for this cool project. It's a hassle to get the original JS project in a TS Feathers 4 project.
Please provide an example how to validate the token.

Thanks

**Comment by MohammedFaragallah** [comment]
You're welcome

all should be the same as the main [lib](https://github.com/feathersjs-ecosystem/feathers-authentication-management) if you face any differences please open an issue

**Comment by dbvcode** [comment]
Got it working.
I was expecting some function to call and not the fact that the authMangement provides it on create.
